/* Source-URL map: reference config, used by the UI to resolve source labels. */
export const U = {
  "pib_edrive": "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2154408",
  "mhi_edrive_pdf": "https://heavyindustries.gov.in/sites/default/files/2025-08/pib2154408.pdf",
  "gst56": "https://gstcouncil.gov.in/sites/default/files/2025-09/press_release_press_information_bureau_0.pdf",
  "niti_elv": "https://niti.gov.in/sites/default/files/2026-01/Enhancing-Circular-Economy-of-End-of-Life-Vehicles-ELVs-in-India.pdf",
  "rbi_mpc": "https://www.rbi.org.in/scripts/annualpolicy.aspx",
  "npci_upi": "https://www.npci.org.in/what-we-do/upi/product-statistics",
  "cv2x_wpc": "https://c-prav.com/2026/06/15/indias-wpc-de-licenses-5-9-ghz-band-for-cellular-vehicle-to-everything-c-v2x-on-board-units/",
  "bee": "https://beeindia.gov.in",
  "morth": "https://morth.nic.in",
  "ais189": "https://morth.nic.in/sites/default/files/ASI/12_Draft_AIS_189_CSMS_DF.pdf",
  "arai": "https://www.araiindia.com",
  "siam": "https://www.siam.in",
  "meity_dpdp": "https://www.meity.gov.in/data-protection-framework",
  "iso26262": "https://www.iso.org/standard/68383.html",
  "mordor": "https://www.mordorintelligence.com",
  "tracxn": "https://tracxn.com",
  "marklines": "https://www.marklines.com",
  "autocarpro": "https://www.autocarpro.in",
  "autosar": "https://www.autosar.org",
  "vahan": "https://vahan.parivahan.gov.in/analytics/",
  "eamrit": "https://e-amrit.niti.gov.in",
  "heavyind": "https://heavyindustries.gov.in",
  "oca": "https://openchargealliance.org",
  "iea": "https://www.iea.org/energy-system/transport/electric-vehicles",
  "sae": "https://www.sae.org",
  "jdpower": "https://www.jdpower.com",
  "certin": "https://www.cert-in.org.in",
  "unece": "https://unece.org/transport/vehicle-regulations",
  "counterpoint": "https://www.counterpointresearch.com",
  "dot": "https://dot.gov.in",
  "cpcb": "https://cpcb.nic.in",
  "sebi": "https://www.sebi.gov.in",
  "rmi": "https://rmi.org",
  "niti": "https://www.niti.gov.in",
  "mckinsey": "https://www.mckinsey.com"
};
