# -*- coding: utf-8 -*-
"""Split the static SearchField.jsx into the live frontend's modules.

The UI code is not edited by hand. It is cut out of the static file at fixed
markers and given imports, so the live board renders with exactly the same
component code as the static one. Only the data half is removed.

    engine.js        GRAD, INK and the V9 engine + static framework constants
    store.js         the board as live ES-module bindings, filled by hydrate();
                     portfolio calibration, recomputed on every hydrate
    sources.js       the U source-URL map (reference config, stays in code)
    SearchField.jsx  the UI, unchanged, with imports in place of the data

ES-module `export let` bindings are live: when hydrate() reassigns DATA, every
module that imported DATA sees the new value. That is what lets the UI code
keep referring to DATA, V8, PORTFOLIO... as plain names.

Usage: python tools/split_frontend.py <static SearchField.jsx>

ONE-TIME MIGRATION. It ran on 2026-09-24. Since then the live frontend is the
source of truth and has diverged (CPI rounding fix); re-running this would
overwrite those changes.
"""
import io
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "frontend" / "src"


def find(lines, pred, start=0, label=""):
    for i in range(start, len(lines)):
        if pred(lines[i]):
            return i
    raise SystemExit(f"marker not found: {label}")


def main(src_path: str) -> None:
    lines = io.open(src_path, encoding="utf-8").read().split("\n")

    i_grad = find(lines, lambda l: l.startswith("const GRAD ="), label="GRAD")
    i_fields = find(lines, lambda l: l.startswith("const FIELDS ="), label="FIELDS")
    i_macro = find(lines, lambda l: l.startswith("const MACRO ="), label="MACRO")
    i_macro_end = find(lines, lambda l: l == "};", i_macro, "MACRO end")
    i_data = find(lines, lambda l: l.startswith("const DATA = {"), label="DATA")
    i_calib = find(lines, lambda l: "PORTFOLIO CALIBRATION" in l, label="calibration") - 1
    i_ui = find(lines, lambda l: "UI atoms" in l, label="UI atoms")
    i_pf = find(lines, lambda l: l.startswith("const PORTFOLIO ="), i_calib, "PORTFOLIO")
    i_rank = find(lines, lambda l: l.startswith("function indexRank"), i_calib, "indexRank")
    i_imports_end = find(lines, lambda l: 'from "recharts";' in l, label="recharts import")

    # ── engine.js ──────────────────────────────────────────────────────────
    engine_src = lines[i_grad:i_fields] + lines[i_macro_end + 1:i_data]
    exported, names = [], []
    for l in engine_src:
        m = re.match(r"^(const|function|let) ([A-Za-z_$][\w$]*)", l)
        if m:
            names.append(m.group(2))
            l = "export " + l
        exported.append(l)
    engine = ("/* V9 scoring engine and static framework constants.\n"
              "   Generated by tools/split_frontend.py from the static board — edit the\n"
              "   generator or the static source, not this file. The Python port in\n"
              "   backend/app/engine/scoring.py is held to it by golden parity tests. */\n"
              + "\n".join(exported).rstrip() + "\n")

    # ── store.js ───────────────────────────────────────────────────────────
    calib = lines[i_calib:i_ui]
    rel_pf, rel_rank = i_pf - i_calib, i_rank - i_calib
    head, body, tail = calib[:rel_pf], calib[rel_pf:rel_rank], calib[rel_rank:]
    body = [re.sub(r"^const (PORTFOLIO(_STATS)?) =", r"\1 =", l) for l in body]
    head = ["export " + l if re.match(r"^(const|function) ", l) else l for l in head]
    tail = ["export " + l if re.match(r"^(const|function) ", l) else l for l in tail]
    store = "\n".join([
        "/* The board, held as live ES-module bindings.",
        "",
        "   main.jsx fetches /api/board and calls hydrate() once before the first",
        "   render. Every module that imported DATA, V8, PORTFOLIO... then sees the",
        "   loaded values, so the UI code reads them exactly as it did when they were",
        "   literals in the static file. */",
        f"import {{ {', '.join(names)} }} from \"./engine.js\";",
        "",
        "export let FIELDS = [], MACRO = {}, DATA = {}, V6 = {}, V7 = {}, V8 = {}, SUB = {};",
        "export let PORTFOLIO = {}, PORTFOLIO_STATS = {};",
        "export let BOARD_AS_OF = null;",
        "",
        *head,
        "function computePortfolio() {",
        *["  " + l if l else l for l in body],
        "}",
        "",
        *tail,
        "",
        "export function hydrate(board) {",
        "  FIELDS = board.FIELDS; MACRO = board.MACRO;",
        "  DATA = board.DATA; V6 = board.V6; V7 = board.V7; V8 = board.V8; SUB = board.SUB;",
        "  BOARD_AS_OF = board.asOf;",
        "  computePortfolio();",
        "}",
        "",
    ])

    # ── sources.js ─────────────────────────────────────────────────────────
    urls = json.loads((ROOT / "backend" / "seed" / "source_urls.json").read_text(encoding="utf-8"))
    sources = ("/* Source-URL map: reference config, used by the UI to resolve source labels. */\n"
               "export const U = " + json.dumps(urls, indent=2, ensure_ascii=False) + ";\n")

    # ── SearchField.jsx ────────────────────────────────────────────────────
    ui = "\n".join([
        *lines[:i_imports_end + 1],
        f"import {{ {', '.join(names)} }} from \"./engine.js\";",
        "import { FIELDS, MACRO, DATA, V6, V7, V8, SUB, PORTFOLIO, PORTFOLIO_STATS, INDEX_KEYS, indexRank, computeAllIndices } from \"./store.js\";",
        "import { U } from \"./sources.js\";",
        "",
        "/* UI of the Search-Field Intelligence board. Generated by",
        "   tools/split_frontend.py from the static board: the component code below is",
        "   the static board's, byte for byte. The data it reads now comes from the API",
        "   via store.js instead of from literals in this file. */",
        "",
        *lines[i_ui:],
    ])

    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in (("engine.js", engine), ("store.js", store), ("sources.js", sources), ("SearchField.jsx", ui)):
        (OUT / name).write_text(text, encoding="utf-8")
        print(f"  {name:16} {text.count(chr(10)):>6} lines")
    print(f"  engine exports: {len(names)}")


if __name__ == "__main__":
    main(sys.argv[1])
